services:
  db:
    image: postgres:latest
    container_name: blog-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5433:5432
    volumes:
      - 'library-postgres:/var/lib/postgresql/data'
    networks:
      - library-network

volumes:
  library-postgres:
    driver: local

networks:
  library-network:
    driver: bridge
    external: true
    name: library-network
